# use an older trusty image, because the newer images cause build errors with
# psycopg2 that comes with CKAN<2.8:
#   "Error: could not determine PostgreSQL version from '10.1'"
# see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

# matrix
python:
  - "2.7"
env:
  - CKANVERSION=2.8.2
  - CKANVERSION=master
# tests
services:
  - postgresql
  - redis-server
install:
  - bash bin/travis-build.bash
  - pip install --user coveralls
script: sh bin/travis-run.sh
after_success:
  - coveralls

# additional jobs
matrix:
  include:
    - name: "Flake8 on Python 2.7"
      dist: xenial    # required for Python 3.7
      cache: pip
      install: pip install --user flake8
      script:
        - flake8 --version
        - flake8 . --count --max-complexity=12 --max-line-length=127 --statistics --exclude ckan,{{ project }}
      python: "2.7"
      # overwrite matrix
      env:
        - FLAKE8=true
        - CKANVERSION=master
notifications:
  slack:
    rooms:
        - secure: BleITOYvW7EOKxAyfPHJrrZ334/HO2wTvWgyh+x0wZb0Xe5rYvpBrNdbbNRW7eUJlZlA9lETFLzfU+EXO4K+VD40pPDIt31/gxElxmRRD+2BBdlbUZd8N1c+puVWnldaIfUQj+1lyK6XBjowJ2XffxknbLpKTNaEyKZBmg3/2AQxBVTEP9VhMLjERNgenv34/NE7TVeu/NYFxOPpzsk5kWAJ2AvuSh+F9M8LBWHregwXyR6pmNqW0cs5u47i1UXU8dSOFxplzR0eCmqEyMliOhE5+18gmWmt5fuxa/h7uDnWxn+WgO4zeKP9odFI3i5RGYSnRvlF9aWnbDpZornBfvfSsayAe+NxE6rro8ZdHtHsV5m3fWS6naSZ/qD/P3z5+0Kcsww5ooRqqkZ9S+iu+++JhqZXWn8poq0poJ+/Wu/zA0r5lsBzyY8Kn8YXEmwMbMfBaogTpFnYOqgmWV3bsyZEVb8T4j17PHsSZJQ5/IjGYTyaVfBgNRR0CZg2F+Ni3TOzlgLoJD9MFOTzYD5ErbAe9y+uYujId7hUgfe8dFvce4KOqu592T1jZ7mwmVOh3htOH9e7wxJ5ir6LeVj9k67g7KT9Fw5oUWfTr0xGtKgzUXGNJoC2T9yRSkvi5uM6T2WUgbKEjThhYDqL5e/zdgBOLr2qIV9nCNeV9m40iEo=
    on_success: change
    on_failure: always
